# Generated by Django 3.1.7 on 2021-03-08 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('periods', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Daily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('modified', models.DateTimeField(auto_now_add=True)),
                ('notes', models.CharField(blank=True, max_length=1000, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='periods.period')),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
    ]
