# Generated by Django 3.1.7 on 2021-03-28 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailies', '0002_auto_20210311_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily',
            name='date',
            field=models.DateField(),
        ),
    ]
