# Generated by Django 3.1.7 on 2021-03-10 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('periods', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='period',
            name='date_from',
        ),
        migrations.AddField(
            model_name='period',
            name='budget',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
            preserve_default=False,
        ),
    ]
