# Generated by Django 3.1.7 on 2021-03-12 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('periods', '0002_auto_20210310_0244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='period',
            old_name='date_to',
            new_name='finish_date',
        ),
        migrations.AddField(
            model_name='period',
            name='date',
            field=models.DateField(auto_now_add=True, default='2020-01-01'),
            preserve_default=False,
        ),
    ]
