# Generated by Django 3.1.7 on 2021-03-28 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('periods', '0003_auto_20210312_0054'),
    ]

    operations = [
        migrations.AddField(
            model_name='period',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
            preserve_default=False,
        ),
    ]
