# Generated by Django 3.1.7 on 2021-03-28 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='theme',
            field=models.CharField(blank=True, choices=[('l', 'Light'), ('d', 'Dark'), ('a', 'Auto')], default='a', max_length=1),
        ),
    ]
