# Generated by Django 3.1.7 on 2021-03-10 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail',
            name='description',
        ),
        migrations.RemoveField(
            model_name='detail',
            name='time',
        ),
    ]
