# Generated by Django 3.1.7 on 2021-03-28 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0002_auto_20210310_1421'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detail',
            options={'get_latest_by': 'created', 'ordering': ['created']},
        ),
    ]
